# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#pool:
#  vmImage: 'Ubuntu 16.04'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#    echo even more stuff $(System.DefaultWorkingDirectory)
#    echo 'I wonder if single quotes will work. Working Directory $(System.DefaultWorkingDirectory)'
#    echo "I wonder if double quotes will work. Working Directory $(System.DefaultWorkingDirectory)"
#  displayName: 'Run a multi-line script'

jobs:
- job: BuildLinuxOS
  strategy:
    maxParallel: 2
    matrix:
      Node9:
        NODE_VERSION: '9.x'
#      Node10:
#        NODE_VERSION: '10.x'

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: |
      echo NODE_VERSION = $(NODE_VERSION)
      echo See https://aka.ms/yaml
    displayName: 'Testing running a multi-line script'

  #Before Install Scripts

  - script: |
      npm config set shrinkwrap false
    displayName: 'Configure npm: Skip updating shrinkwrap / lock'

  - script: |
      npm rm --silent --save-dev connect-redis
    displayName: 'Remove all non-test dependencies: Remove example dependencies'

  - script: |
      if [[ "$(cut -d. -f1 <<< "$NODE_VERSION")" -lt 6 ]]; then
        npm install --silent --save-dev mocha@3.5.3
      fi
    displayName: 'Setup Node.js version-specific dependencies: mocha for testing: use 3.x for Node.js < 6'

  - script: |
      if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 4 ]]; then
        npm install --silent --save-dev supertest@2.0.0
      fi
    displayName: 'Setup Node.js version-specific dependencies: supertest for http calls: use 2.0.0 for Node.js < 4'
    
  - script: |
      if [[ -d node_modules ]]; then
        npm prune
        npm rebuild
      fi
    displayName: 'Setup Node.js version-specific dependencies: Update Node.js modules: Prune and rebuild node_modules'

  #Testing
  - script: |
      npm run test-ci
    displayName: 'Run test script'