# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#pool:
#  vmImage: 'Ubuntu 16.04'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#    echo even more stuff $(System.DefaultWorkingDirectory)
#    echo 'I wonder if single quotes will work. Working Directory $(System.DefaultWorkingDirectory)'
#    echo "I wonder if double quotes will work. Working Directory $(System.DefaultWorkingDirectory)"
#  displayName: 'Run a multi-line script'

jobs:
- job: BuildLinuxOS
  strategy:
    maxParallel: 2
    matrix:
      Node9:
        NODE_VERSION: '9.x'
      Node10:
        NODE_VERSION: '10.x'

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: |
      echo NODE_VERSION = $(NODE_VERSION)
      echo See https://aka.ms/yaml
    displayName: 'Testing running a multi-line script'

  - script: |
      npm config set shrinkwrap false
    displayName: 'Configure npm: Skip updating shrinkwrap / lock'
