#TODO: Add Coveralls step, just for Linux
#TODO: Publish coversalls files, just because
steps:
- powershell: |
    $nodeVersion = "$(NODE_VERSION)"
    $nodeMajorVersion = $nodeVersion.split(".")[0]
    Write-Output ("##vso[task.setvariable variable=NodeMajorVersion;]$nodeMajorVersion")
  displayName: "Get Major Version Number of NodeJS Using PowerShell"     

#Start The Before Install Tasks
- script: npm config set shrinkwrap false
  displayName: 'Configure npm: Skip updating shrinkwrap / lock'

- script: npm rm --silent --save-dev connect-redis
  displayName: 'Remove all non-test dependencies: Remove example dependencies'

- script: npm install --silent --save-dev mocha@3.5.3
  displayName: 'Setup Node.js version-specific dependencies: mocha for testing: use 3.x for Node.js < 6'
  condition: lt(variables['NodeMajorVersion'], 6)

- script: npm install --silent --save-dev supertest@2.0.0
  displayName: 'Setup Node.js version-specific dependencies: supertest for http calls: use 2.0.0 for Node.js < 4'
  condition: lt(variables['NodeMajorVersion'], 4)
    
- powershell: |
    # Prune & rebuild node_modules
    if (Test-Path -Path node_modules) {
        npm prune
        npm rebuild
      }
  displayName: 'Setup Node.js version-specific dependencies: Update Node.js modules: Prune and rebuild node_modules'

#Finish With Before Install Tasks. Time to install dependencies

#These two steps are required because the language command in Travis sets the node version, 
#and also does an npm install and an npm test
- task: NodeTool@0
  displayName: 'Node Tool install $(NODE_VERSION)'
  inputs:
    versionSpec: '$(NODE_VERSION)'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

#Testing
- script: |
    npm run test-ci
  displayName: 'Run test script'

- script: |
    npm run lint
  displayName: 'Run linting'