steps:
- powershell: |
    $rc = "$(NODE_VERSION)"
    $rc2 = $rc.split(".")[0]
    Write-Output ("##vso[task.setvariable variable=OutputVar1;]$rc2")
   
  displayName: "Get Major Version Number Using PowerShell"     

- powershell: |
    Write-host $env:OUTPUTVAR1
    Write-Host $(Agent.OS)
      
  displayName: "Output Test"    