jobs:
- job: Linux_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 0.12:
        NODE_VERSION: '0.12'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - powershell: |
      $nodeVersion = "$(NODE_VERSION)"
      $nodeMajorVersion = $nodeVersion.split(".")[0]
      Write-Output ("##vso[task.setvariable variable=NodeMajorVersion;]$nodeMajorVersion")
    displayName: "Get Major Version Number of NodeJS Using PowerShell"

  - script: |
      curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install.sh
      bash install.sh
      source ~/.profile
      ls
      nvm ls-remote
    displayName: "Install NVM"

  - script: node --version
    displayName: "Node Version"

  - script: npm --version
    displayName: "NPM Version"

  - script: nvm --version
    displayName: "nvm version"

