jobs:
- job: Windows_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 1.8:
        NODE_VERSION: '1.8'

  continueOnError: false
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  # - task: NodeTool@0
  #  displayName: "Use Node $(NODE_VERSION)"
  #  inputs:
  #    versionSpec: $(NODE_VERSION)
  #    checkLatest: true

  - powershell: |
      $iojsUrl = "https://iojs.org/dist/v1.8.4/iojs-v1.8.4-x64.msi"
      Invoke-WebRequest -Uri $iojsUrl -OutFile (Join-Path "$(agent.tempDirectory)" "mickey.msi")
      #$x = (Join-Path "$(agent.tempDirectory)" "tmp")
      dir $(agent.tempDirectory)
      mickey.msi /passive
      

