jobs:
- job: Windows_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 1.8:
        NODE_VERSION: '1.8'
      

  continueOnError: false
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  # - task: NodeTool@0
  #  displayName: "Use Node $(NODE_VERSION)"
  #  inputs:
  #    versionSpec: $(NODE_VERSION)
  #    checkLatest: true

  - powershell: |
      #$iojsUrl = "https://iojs.org/dist/v2.4.0/iojs-v2.4.0-x64.msi"
      #$file = Join-Path "$(agent.tempDirectory)" "iojs-v2.4.0-x64.msi"
      #Invoke-WebRequest -Uri $iojsUrl -OutFile $file
      #dir $(agent.tempDirectory)
      ##Set variables and attempt to install
      #$logFile = Join-Path "$(agent.tempDirectory)" "install.log"
      ##$targetDir = "$(agent.tempDirectory)"
      #$MSIArguments = @("/i", "$file", "/qn", "/norestart", "/L*v", $logFile, "ADDLOCAL=ALL", "REMOVE=NodePerfCtrSupport,NodeEtwSupport")
      #Start-Process "msiexec.exe" -ArgumentList $MSIArguments -Wait -NoNewWindow
      #dir $(agent.tempDirectory)
      #$iojsDir = "c:\Program Files\iojs"
      #dir "$iojsDir"
      ##more $logFile
      #$newPath = "$iojsDir;$env:Path"
      #$newPath
      #Write-Host "##vso[task.setvariable variable=PATH;]$newPath";
      #$env:Path
      #node --version

      $env:PROCESSOR_ARCHITECTURE
      $iojsValues = '1.8','2.4','3.3'
      if ($(NODE_VERSION) -In $iojsValues)
      {
        Write-Information ("iojs")
        $iojsUrl = "https://iojs.org/dist/index.json"
        $iojsList = Invoke-WebRequest -Uri $iojsUrl
        $iojsConverted = ConvertFrom-Json -InputObject $iojsList
        $matchValues = $iojsConverted | Where-Object {$_.version -match "v$(NODE_VERSION)"}
        $x = "$matchValues[0]"
        $ver = $z.version
        $ver
        $msi = "iojs-$ver-x64.msi"
        $msi
        $iojsUrl = "https://iojs.org/dist/$ver/$msi"
        $iojsUrl
        $file = Join-Path "$(agent.tempDirectory)" "$msi"
        Invoke-WebRequest -Uri $iojsUrl -OutFile $file
        dir $(agent.tempDirectory)
        ##Set variables and attempt to install
        $logFile = Join-Path "$(agent.tempDirectory)" "install.log"
        #$targetDir = "$(agent.tempDirectory)"
        $MSIArguments = @("/i", "$file", "/qn", "/norestart", "/L*v", $logFile, "ADDLOCAL=ALL", "REMOVE=NodePerfCtrSupport,NodeEtwSupport")
        Start-Process "msiexec.exe" -ArgumentList $MSIArguments -Wait -NoNewWindow
        dir $(agent.tempDirectory)
        $iojsDir = "c:\Program Files\iojs"
        dir "$iojsDir"
        #more $logFile
        $newPath = "$iojsDir;$env:Path"
        $newPath
        Write-Host "##vso[task.setvariable variable=PATH;]$newPath";
        $env:Path
        node --version
      }
      

  - powershell: |
      $env:Path
      node --version

