jobs:
- job: Windows_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 2.4:
        NODE_VERSION: '2.4'

  continueOnError: false
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  # - task: NodeTool@0
  #  displayName: "Use Node $(NODE_VERSION)"
  #  inputs:
  #    versionSpec: $(NODE_VERSION)
  #    checkLatest: true

  - powershell: |
      $iojsUrl = "https://iojs.org/dist/v2.4.0/iojs-v2.4.0-x64.msi"
      $file = Join-Path "$(agent.tempDirectory)" "iojs-v2.4.0-x64.msi"
      Invoke-WebRequest -Uri $iojsUrl -OutFile $file
      dir $(agent.tempDirectory)

  - powershell: |
      node --version

