jobs:
- job: Windows_MustPass
  strategy:
    maxParallel: 10
    matrix:
      Node 1.8:
        NODE_VERSION: '1.8'

  continueOnError: false
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  # - task: NodeTool@0
  #  displayName: "Use Node $(NODE_VERSION)"
  #  inputs:
  #    versionSpec: $(NODE_VERSION)
  #    checkLatest: true

  - powershell: |
      $iojsUrl = "https://iojs.org/dist/v1.8.4/iojs-v1.8.4-x64.msi"
      $file = Join-Path "$(agent.tempDirectory)" "mickey.msi"
      $log = Join-Path "$(agent.tempDirectory)" "install.log"
      Invoke-WebRequest -Uri $iojsUrl -OutFile $file
      dir $(agent.tempDirectory)

      Start-Process -FilePath "msiexec.exe" -Wait -PassThru -ArgumentList @("/a", "$file", "/qb", "TARGETDIR=$(agent.tempDirectory)", "/L*v $log")

      dir $(agent.tempDirectory)
      more $log

  - powershell: |
      node --version

